class MyException extends Exception {
    private String Teks;
    
    MyException(String s) {
        Teks = "Exception generated by: " + s;
        System.out.println(Teks);
    }
}

class Eksepsi {
    // Mengubah Exception menjadi MyException agar spesifik dan sinkron dengan blok catch
    static void tampil(String s) throws MyException {
        System.out.println("Tampil");
        if (s.equals("amir")) {
            throw new MyException(s);
        }
        System.out.println("OK!");
    }

    public static void main(String[] args) throws MyException {
        try 
        {
            tampil("ali");
            tampil("amir");
        } 
        catch (MyException ex) 
        {
            System.out.println("Tangkap: " + ex);
        }
    }
}
